### ISSUE TITLE
Error on first claim - no events belonging to 0x...

### ISSUE THREAD

**Issue by moeadham** [nexusdev/feedbase#21]
root@---:~# date && feedbase claim
Sun Jul 24 21:47:46 EDT 2016
feedbase: error: no events belonging to 0x35d50f53dc49f372f6ef0e75563a28b06f594fa6

Output from geth logs:
I0724 21:47:48.047417 eth/api.go:1193] Tx(0x6af2d6fc69431b382afd424f70f03351f04c013894c446491c10991a716ae19f) to: 0xd7898998dc9bd43425ffb383ebd663e2c60a5601

So, the transaction was sent ~2 seconds later.
http://etherscan.io/tx/0x6af2d6fc69431b382afd424f70f03351f04c013894c446491c10991a716ae19f

Attempting several more times didn't help. It took 3 minutes to spit out that error.

Not sure if there is a way to enable verbose logging or anything. Should I try upping the timeout?
https://github.com/nexusdev/feedbase/blob/master/bin/feedbase#L54

**Comment by dbrock** [comment]
Yeah, I noticed that too, really annoying.

I gave up on trying to fix it because it was happening so randomly and just put an apology note in the README instead, but look into it again tonight now that I know that other people have the same problem.

Thanks!

**Comment by moeadham** [comment]
Great, thanks! I have a 100% failure rate. Happy to help debug, we have been looking for something like this for some time.

**Comment by moeadham** [comment]
Hi @dbrock 

Here is the output:

root@---:~# feedbase --version && date && feedbase claim
0.6.1
Thu Jul 28 12:25:13 EDT 2016
Sent 0xb4ffe5d34d7dc9e790099818d0f0cfbc072b6121319bbefaa0ddb29bacc198bc.
Waiting for confirmation...
feedbase: error: timed out

Geth- 
VERSION:
   1.4.10-stable

I0728 12:25:14.464440 eth/api.go:1193] Tx(0xb4ffe5d34d7dc9e790099818d0f0cfbc072b6121319bbefaa0ddb29bacc198bc) to: 0xd7898998dc9bd43425ffb383ebd663e2c60a5601

**Comment by shayanb** [comment]
So me and @moeadham figured out what the issue was here, on testnet geth wasn't synced so that was the case there, however on mainnet, there hasn't been a contract created on the address that is included in feedbase binary which is `0xd7898998dc9bd43425ffb383ebd663e2c60a5601` (and this is actually the address for the testnet contract, so... it should not work on mainnet).

**Comment by dbrock** [comment]
@shayanb: awesome, thanks!
